data/db/toLoad/output000001.nq.gz
the to load directory wasn't added properly through git lfs and also wasn't necessary for the app to work properly
=> [LMB-15] clear toload directory

config/authorization/config.ex, config/resources/domain.lisp, config/resources/master-files-domain.lisp
This removes all SEAS rules that are no longer necessary after extracting lokaal mandatenbeheer out of loket
You can verify that everything still works by checking this PR out locally, restarting the database service and opening/editing mandates from the frontend interface. upon reload your changes should have persisted.
=> [LMB-28] chore: review seas rules inherited from loket

.gitignore, config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
This can be tested by first adding example data to a stream, e.g. a person stream with the following post:
```
curl --request POST \
--url http://localhost:6666/person \
--header 'Content-Type: text/turtle' \
--data '<https://example.org/person/80325> a <http://xmlns.com/foaf/0.1/Person>;
<http://xmlns.com/foaf/0.1/name> "John Lennon";
<http://schema.org/birthDate> "1940-10-09"^^<http://www.w3.org/2001/XMLSchema#date>;
<http://schema.org/spouse> <http://dbpedia.org/resource/Cynthia_Lennon>.'
```
It can then be fetched using:
```
curl --request GET \
--url http://localhost:90/streams/ldes/person/1 \
--header 'Accept: text/turtle' \
--data '<https://example.org/person/80325> a <http://xmlns.com/foaf/0.1/Person>;
<http://xmlns.com/foaf/0.1/name> "John Lennon";
<http://schema.org/birthDate> …
```
=> add fragmentation producer

README.md, config/authorization/config.ex, config/dispatcher/dispatcher.ex, config/migrations/2024/20240319110700-add-vendor-login.sparql, config/sparql-authorization-wrapper/filter.js, docker-compose.dev.yml, docker-compose.yml, queries/vendor-access/add-vendor-key.sparql
This adds an authenticated sparql endpoint that vendors can use to have read access to all the data visible to an organization.
I've attached a bruno collection that can be used to test this service.
Note that the sparql query i used in bruno uses the plain sparql syntax which isn't supported in the standard mu-auth yet (see https://github.com/mu-semtech/mu-authorization/pull/20/files), you can replace it by a query param with the url encoded sparql query instead.
[vendor sparql.json](https://github.com/lblod/app-lokaal-mandatenbeheer/files/14652060/vendor.sparql.json)
=> allow read access for vendors through authenticated sparql endpoint

config/ldes-delta-pusher/dispatch.ts, config/ldes-delta-pusher/publisher.ts
LMB-365
Items in LDES contain the history information and are added twice: once for the history information being added and once for the original change.
1. Open a fraction
2. Change the label using the fraction form
3. wait 10 sec
4. Look in `data/ldes-feed/..` see if the label is there only once and the previous values aren't present in the latest version
=> LMB-365: Duplication in ldes

config/migrations/2024/20240412091121-fix-onafhankelijke-fractie.sparql
This can be checked if you go to the ember debug window and check if the onafhankelijke fractie in e.g. Gemeente Aalst or OCMW Aarschot is effectively of the fractietype onafhankelijk.
=> add migration to fix fractietype of onafhankelijke fracties

config/resources/domain.lisp
Resources was crashing because domain.lisp still imported abstract-resources.lisp which was removed.
=> remove abstract-resources from domain.lisp

config/migrations/2024/20240412000000-mandataris-publication-status.sparql, config/migrations/2024/20240424000000-mandataris-publication-status-order.sparql, config/resources/external-mandaat.lisp
We want to be able to show the mandataris publication statuses in a consistent order, regardless of the order in which they were inserted into the database. This can be achieved by adding an extra sh:order triple to the concepts in the publication status migration. These triples will then be used in the frontend for manual sorting.
Explanation in frontend PR
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/184
=> Add sh:order to mandataris publication status concept scheme

config/ldes-delta-pusher/handle-mandataris-type.ts, config/ldes-delta-pusher/handle-regular-types.ts, config/ldes-delta-pusher/handle-types-util.ts, config/ldes-delta-pusher/publisher.ts, config/resources/external-contact.lisp, docs/LDES.md
Merges the ldes streams we produced up till now so one stream has all types that we want to publish (mandaten, mandatarissen, fracties,...). 
Then publish 3 different versions of those streams: 
- public: everything in abb stream except sensitive data (like rrn identifiers)
- abb: everything that matches the model
- internal: everything (currently only the model classes but this can be extended later)
none of these streams are secured yet.
- checkout this pr, remove your ldes data folder's contents (keep the folder).
- create a person
- modify a fraction
- both items should be present in the ldes streams. The identifier should only be present in the internal and abb streams. If you want to check that only the data that matches the model is present, remove a predicate from a type (e.g. …
=> merge ldes streams into single stream, but publish 3 versions

config/form-content/mandataris-new/form.ttl
The mandataris-new form should also filter the display types according to the mandataris being Burgemeester or not, in the same way that it is done in mandataris-edit.
- Go to the create new mandatee form
- Select the Burgemeester mandaat
- "Aangewezen" should be available in the status selector
- Change the mandaat to something else
- "Aangewezen" should not be available in the status selector
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/193
=> mandataris-new Form Also Has Custom Status Display Type

config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
This adds the new mandataris service (https://github.com/lblod/mandataris-service) to the app. The service doesn't do anything yet.
Your app starts when the mandataris service is used (be sure to use the right profile if using the dev compose)
=> add mandataris service to app and dispatcher

config/ldes-delta-pusher/catchUp.ts, config/ldes-delta-pusher/dispatch.ts, config/ldes-delta-pusher/handle-mandataris-type.ts, config/ldes-delta-pusher/handle-regular-types.ts, config/ldes-delta-pusher/publisher.ts, config/migrations/2024/20240430082000-add-modified.sparql, docker-compose.yml
This sets a dct:modified for all concepts we are interested in and configures the ldes-delta-pusher to push all changes to the ldes stream that it missed (done by comparing the dct:modified of concepts with the last one seen when the pusher was alive, if any).
- remove your data/ldes-feed/* files/folders
- pull this pr and restart the migrations service so it runs the latest migration that is included
- your data now has a dct:modified for all concepts
- modify a random mandataris so you have a later modified date and the safety run the pusher does doesn't add all concepts twice (optional, but recommended)
- kill, rm and restart the ldes-delta-pusher
- see the ldes-stream files increase in count and when done, verify that the last change you made is indeed in the stream
=> allow ldes to catch up after restarting

config/delta/modified.js, config/delta/rules.js, config/modified/config.ts, docker-compose.dev.yml, docker-compose.yml
adds a new service to track modification dates on all interesting concepts.
- clone the https://github.com/lblod/track-modified-service repo for local dev and start it there, or disable the debug profile in the dev drc
- up the docker compose (restart the delta service)
- update a concept, e.g. mandataris
- see that things that are modified along the way (e.g. geboorte) also receive a modified even if we didn't add this through the frontend or the form content service
- see that there is no infinite loop of deltas going on that keep setting the modified date
=> add new service to track modification date on all interesting concepts

config/authorization-wrapper/filter.js, config/authorization-wrapper/router.js, config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml, queries/vendor-access/add-vendor-key.sparql
Adds an authorization layer on top of our ldes feed. That way only the public ldes is publically accessible and to use the abb or internal ldes instances you need to be signed in with a user that has the right impersonation rights. Currently both abb and internal are the same one.
Try and access the public, abb and internal ldes streams page 1. Notice that it only works for the public one.
Run the example query to give the demo vendor access to these endpoints.
Use the vendor login process to log in as an authorized user. Then access all of those pages again and notice they all work.
Here is a postman collection that allows you to perform these steps:
[ldes example.json](https://github.com/lblod/app-lokaal-mandatenbeheer/files/15296330/ldes.example.json)
=> add authorization layer on top of ldes

docker-compose.yml
Bump to 0.0.3 because this version does have a related docker hub image. It is functionally the same as 0.0.2
Walk through the app and see if all mandataris related functionality still works
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/153
=> Bump mandataris service to 0.0.3

config/form-content/bestuursorgaan-ext-example/form.ttl, config/form-content/bestuursorgaan/form.ttl, config/form-content/bestuursperiode/form.ttl, config/form-content/contactinfo/form.ttl, config/form-content/functionaris-edit/form.ttl, config/form-content/functionaris-new/form.ttl, config/form-content/mandaat/form.ttl, config/form-content/mandataris-edit/form.ttl, config/form-content/mandataris-new/form.ttl, config/form-content/persoon/form.ttl
A lot of entities are created through forms, as some fields need to be required or must be positive values these need to be updated with some constraints.
Tim wrote a mail with the required validations => see mailbox `Restricties op form fields` op 28-05-24
Follow the email and see if all validations are added to the application
Aantal houders cannot be negative
Update or create mandataris has three more constraints
=> LMB-147: Add restrictions to forms

config/migrations/2024/20240627000000-update-bestuursorganen-binding-end.sparql
Our bestuursorganen(InTijd) need a more accurate end date. This is the case for the current and previous bestuursperiode.
Run the following querries (separately) to see the updated `bindingEinde`s for the bestuursorganenInTijd of both bestuursperiodes.
```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT *
WHERE {
GRAPH ?g {
?bestuursorgaanInTijd ext:heeftBestuursperiode bestuursperiode:a2b977a3-ce68-4e42-80a6-4397f66fc5ca; # 2019 - 2025
mandaat:bindingStart ?bindingStart;
mandaat:bindingEinde ?bindingEinde.
}
}
SELECT *
WHERE {
GRAPH ?g {
?bestuursorgaanInTijd ext:heeftBestuursperiode …
```
=> Add binding end for bestuursorganenInTijd in current and previous bestuursperiode

config/migrations/2024/20240704115947-replace-verhinderd-titelvoerend.sparql
Currently we only allow users in the frontend to set the status titelvoerend on a mandate, verhinderd is no longer possible. This migration also updates old data in our application where burgemeester could still have the status verhinderd.
Two possible tests:
Go to the following link in the gemeente Aalst and see that the status of this burgemeester is indeed titelvoerend, before running the migration it was verhinderd.
You could also check this query no longer has results (this is a bit cheating however, since this exact query is used to update the statusses...):
```
prefix mandaat:	<http://data.vlaanderen.be/ns/mandaat#> 
prefix org: <http://www.w3.org/ns/org#>
SELECT DISTINCT *
WHERE {
GRAPH ?g {
?mandataris org:holds ?mandaat;
mandaat:status …
```
=> Migration to update burgemeester status verhinderd to titelvoerend

config/migrations/2024/20240703001144-tmp-ocmw-bestuursorganen.sparql
Before fake ocmw bestuursorganen (bestuursorganen that normally belong to an ocmw bestuurseenheid, but are copied to the gemeente bestuurseenheid to prepare a new legislature) had the same id as their original bestuursorgaan. This is resolved in this PR by generating new uuids.
Unfortunately you should again start with a clean database, but this is the last time I'm making updates to existing migrations.
If you run the following query, you should see that ids and uris of new bestuursorganen and bestuursorganen in de tijd are unique.
```
prefix mandaat:	<http://data.vlaanderen.be/ns/mandaat#> 
prefix besluit:	<http://data.vlaanderen.be/ns/besluit#> 
prefix ext: <http://mu.semte.ch/vocabularies/ext/>
prefix mu: <http://mu.semte.ch/vocabularies/core/>
SELECT DISTINCT ?bestuursorgaan …
```
=> create new uuids fake ocmw bestuursorganen

config/form-content/mandataris-ext/form.ttl
Add new form which adds beleidsdomeinen to the mandataris new form. These are only showed for the right mandates, due to the beleidsdomeinen custom component. This is not done as an extension as there are some issues with the relative path or with the generator when extending forms.
Restart form-content service and check if the form is indeed in the forms route. If you try to create a new form entity with this form, you won't see the beleidsdomeinen, as the mandate selector does not really work in this route (no selected bestuursorgaan). You can see the beleidsdomeinen field in the form if you try to edit a mandataris which already has a mandate schepen or burgemeester. Or you can just try to test this with the installatievergadering redesign, which uses this form.
- …
=> LMB-613 add new form with mandataris + beleidsdomeinen v2

config/delta/decisions.js, config/form-content/mandataris-edit/form.ttl, config/resources/external-mandaat.lisp
Updating the delta rule. Callback endpoint has changed in the mandataris service + we are now isting on the predicate `http://mu.semte.ch/vocabularies/ext/bekrachtigtAanstellingVan` so we get `?artikel <http://mu.semte.ch/vocabularies/ext/bekrachtigtAanstellingVan> ?mandataris` in our changesset of the delta.
Run the app with the the mandataris service and the LMB app on the correct branches.
- https://github.com/lblod/mandataris-service/pull/23
=> LMB-524 | Only process mandatrissen with a besluit 

config/form-content/mandataris-edit/form.ttl, config/form-content/mandataris-ext/form.ttl, config/form-content/mandataris-new/form.ttl
Mandaat and person should always be required. We are adding this configuration to the ttl forms.
Checkout this PR and connect with the PR in the frontend. Try creating or updating a mandataris without a person, fractie or mandaat. (Or all of them as seen in the picture in frontend PR)
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/274
=> LMB-553 |Make mandaat, person and selector required

config/migrations/local/20240701091059-tmp-bestuursorganen.sparql
The burgemeester mandaat for bestuursperiode 2025-heden got split into two different mandates for burgemeester and college burgemeester and schepenen. This PR solves this.
Unfortunately this is an update of a existing migration, which means you should clear your existing database.
=> fix tmp bestuursorganen migration

config/form-content/mandataris-edit/form.ttl, config/form-content/mandataris-new/form.ttl, config/resources/external-mandaat.lisp
Extend the person domain with an inverse relation to verkiezingsresultaat and change the orde rof persoon and mandaat field. You should alwyas first select a mandaat before you can select a person.
Togheter with the frontend.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/305
=> LMB-552 | Add inverse relation from person to verkiezingsresultaat

config/ldes-delta-pusher/dispatch.ts, config/ldes-delta-pusher/handle-decision-type.ts
Add the besluiten and or artikels to the LDES stream when it has predicate _mandaat:bekrachtigtAanstellingVan_ of _mandaat:bekrachtigtOntslagVan_
Create a besluit and artikel without a predicate jsut the besluit or artikel type and two with a predicate
https://github.com/lblod/app-lokaal-mandatenbeheer/pull/192#issuecomment-2309813050
=> LMB-683 |Add besluiten & artikels to ldes

.gitignore, scripts/loket-to-lmb-transform/.gitignore, scripts/loket-to-lmb-transform/Dockerfile, scripts/loket-to-lmb-transform/README.md, scripts/loket-to-lmb-transform/app.ts, scripts/loket-to-lmb-transform/constants.ts, scripts/loket-to-lmb-transform/deleteUnwantedInstances.ts, scripts/loket-to-lmb-transform/deleteUnwantedTypes.ts, scripts/loket-to-lmb-transform/docker-compose.export.yml, scripts/loket-to-lmb-transform/docker-compose.purge-public.yml, scripts/loket-to-lmb-transform/docker-compose.transform.yml, scripts/loket-to-lmb-transform/dropUnimportantGraphs.ts, scripts/loket-to-lmb-transform/moveTypesOutOfPublic.ts, scripts/loket-to-lmb-transform/package-lock.json, scripts/loket-to-lmb-transform/package.json, scripts/loket-to-lmb-transform/writeImportantGraphs.ts
This script transforms a loket db to a database that can be used to create a toLoad for an LMB database. The how to is in the readme
Start from a dump from a loket db. Run it in your virtuoso (don't run our migrations). Then run this script. Once done, create a dump file and transform it into a toLoad folder. Use that for starting a new instance of the LMB db.
=> script to transform loket to lmb

config/cl-authorization/config.lisp, config/dispatcher/dispatcher.ex, config/resources/external-besluit.lisp, config/resources/external-mandaat.lisp
Creating an abstract _rechtsgrond_ resource that will hold the _bekrachtigtAanstellingVan_ & _bekrachtigtOntslagVan_. Added an inverse relation for both properties of rechtsgrond on mandataris.
Create a besluit and link a mandataris to the besluit. The mandataris should hold the besluit.
```sparql
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
INSERT DATA {
GRAPH <http://mu.semte.ch/graph/organizations/974816591f269bb7d74aa1720922651529f3d3b2a787f5c60b73e5a0384950a4/LoketLB-mandaatGebruiker> {
<http://decision-5> a besluit:Besluit;
mu:uuid """fc7cacae-c2b6-465f-8005-c009e82b4d33""";
mandaat:bekrachtigtAanstellingVan …
```
=> LMB-607 | Update domain with link from mandataris to besluit/artikel

config/migrations/local/20240829152518-remove-duplicate-bestuursorgaan-names.sparql
Removes duplicate skos preflabels of bestuursorganen.
It is configured manually which preflabel needs to be removed, now we just remove the ones that end with "-edit" or don't have "(voor fusie)", this covers all values in the test data, might need to change later on.
You can use the following query to find bestuursorganen that have duplicate skos:prefLabels
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?bestuursorgaan ?label1 ?label2 WHERE {
{
SELECT ?bestuursorgaan WHERE {
GRAPH ?g {
?bestuursorgaan a besluit:Bestuursorgaan ;
skos:prefLabel ?o .
}
}
GROUP BY ?g ?bestuursorgaan
HAVING (COUNT(?o) > 1)
}
?bestuursorgaan skos:prefLabel ?label1 ;
skos:prefLabel ?label2 .
FILTER (?label1 != ?label2)
FILTER …
```
=> LMB-587 add migration to remove duplicate skos reflabels bestuursorganen

config/ldes-delta-pusher/handle-regular-types.ts, config/ldes-delta-pusher/handle-types-util.ts, config/ldes-delta-pusher/publisher.ts, docker-compose.yml
faster initial dump of ldes stream, paginated, also fix some things regarding persons being public
This requires the version of the ldes stream from the linked PR
Delete the contents of your data/ldes-stream folder (but keep the folder)
Toggle the WRITE_INITIAL_STATE variable to true 
start the ldes-delta-pusher service to write the initial state
inspect the resulting files
upload the resulting files to a graph of your choice and run a query to verify that all instances of the target type are present e.g.:
```
PREFIX person: <http://www.w3.org/ns/person#>
SELECT * WHERE {
GRAPH ?g {
?s a mandaat:Mandataris.
FILTER NOT EXISTS {
GRAPH <http://localhost/temp/ldes/public> {
?member dcterms:isVersionOf ?s.
}
}
}
FILTER (?g != …
```
=> faster initial dump of ldes stream, paginated, also fix some things regarding persons being public

config/ldes-delta-pusher/initialization.ts, config/ldes-delta-pusher/publisher.ts, config/migrations/2024/20240905101700-mark-bestuurseenheid-graphs.sparql, docker-compose.yml
When publishing deltas to the ldes feed, we should also publish the bestuurseenheid that is linked to the concept. This makes it easier for consumers like GN to put the information in the right graph(s).
Do an update to different concepts (mandataris, person, ...) and verify that the concept is published with the bestuurseenheid link in the different feeds.
This requires extra hooks in the initialization of the ldes feed: https://github.com/redpencilio/ldes-delta-pusher-service/pull/7
=> track the bestuurseenheid when publishing on ldes

config/form-content/bestuursorgaan/form.ttl
Removing the property group title because the modal in the frontend already has a title
Press the button add orgaan on the organen overview.
The modal should look like this
=> LMB-593: remove property group title for adding bestuursorgaan

config/ldes-delta-pusher/publisher.ts, config/resources/external-mandaat.lisp, config/resources/verkiezingen.lisp
Swtich the relation and make sure it comes on the ldes-feed
Backend resource does not brake + frontend splitting fractie
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/320
=> LMB-732: Switch kandidaatlijst -> fractie relation

config/form-content/mandataris-edit/form.ttl, config/resources/external-besluit.lisp
remove the link to besluit from the correct mandataris form + update the domain of rechtsgrond so instead of string properties it is a relation to a mandataris
Follow the frontend PR test steps
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/327
=> LMB-698 | better handling of mandataris bekrachtigd

config/migrations/2024/20240910114100-set-end-date-for-bestuursperiode-2019-2025.sparql
We want to set the enddate of the current bestuursorganen to 2025-01-01 instead of 2024-12-06
This query should give you all bestuursorganen from current bestuursperiode. The ?einde should be set to 2025-01-01
```
select distinct ?bestuursorgaan ?start ?einde where {
?bestuursperiode a  lmb:Bestuursperiode;
lmb:startYear 2019 ;
lmb:endYear  2025 .
?bestuursorgaan a besluit:Bestuursorgaan;
lmb:heeftBestuursperiode ?bestuursperiode;
mandaat:bindingStart ?start;
mandaat:bindingEinde ?einde.
}
```
=> LMB-438 | Add migration removing end date and adding new to 2025-01-01

docker-compose.mac.yml
Removed the service from `docker-compose.mac.yml`, couldn't really find it any other place (got removed here https://github.com/lblod/app-lokaal-mandatenbeheer/pull/201).
Maybe check if you can find any other reference to the service.
=> remove person-uri-for-secial-security-number service

config/resources/external-besluit.lisp
As the frontend only wants to set the linktobesluit on the mandataris and not link it directly with the besluit, this commit can be reverted.
Follow the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/327
=>  LMB-698 | Make rechtsgrond have properties instead of relation to aanstelling or ontslag

config/migrations/2024/20240000000002-add-mock-users.sparql, config/migrations/2024/20240910082600-add-politieraad-to-andere.sparql, scripts/loket-to-lmb-transform/deleteUnwantedInstances.ts
reinstate deputatie and politieraad
log in as vlaams brabant, see the deputatie is still there.
politieraad is still there in the data after the transform but is linked to a bestuurseenheid that we don't support yet. Still we should already add it back in so we can add the bestuurseenheid after
=> reinstate deputatie and politieraad

docker-compose.yml
A volume seems to be missing to be able to write the initial state, this PR adds this configuration to the docker compose.
Without this line the "WRITE_INITIAL_STATE" does not work.
=> add missing volume ldes-delta-pusher

config/migrations/2024/20241003084700-cleanup-local-bestuursorganen.sparql, config/migrations/2024/20241003092900-cleanup-local-bestuursorganen.sparql
This removes the old 'local' bestuursorganen that were created. I ran a query and you can recognize them by their end date:
```
SELECT * WHERE {
?s mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/822433205a41ef80005686050d7ab9e3a207cf07c0c1b3bbe5d879e7dcf363e9>.
?s ?p ?o.
}order by ?s ?p
#+end_src
#+RESULTS:
| s                                                                                                          | p                                                            | o                                                                                                          |
|------------------------------------------------------------------------------------------------------------+--------------- …
```
=> remove local bestuursorgaan instances that were created before

config/form-content/mandataris-edit/form.ttl
The start and enddate need to be validated. Added the custom validation to the validations of the fields. This validation is created in the frontend.
Follow the frontend how to test
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/330
=> lmb-700: add custom validation to the start and enddate for mandataris form

config/resources/external-besluit.lisp
This is needed so we can link it to a bestuurseenheid (mu-auth doesn't let us go the other way)
see: https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/342
=> add relation from bestuurseenheid-contact to bestuurseenheid

queries/kalliope/persoons-info-burgemeesters.sparql
This query returns person-uri, voornaam, achternaam, geboortedatum and gemeente-uri as requested. It returns the results for all person instances that were ever linked to a kieslijst
run the query against your virtuoso
=> keep the query we will use to supply kalliope with their data in git

config/migrations/2024/20241008131100-migrate-contact-info.sparql
Add a migration to migrate the contact info that is used in loket to the implementation that we use in LMB. This is needed because we can't update the info on the bestuurseenheid, but we want users to be able to do that, so we need to add a resource the users can manage themselves.
Pretty difficult to test, because we don't have the data from loket (probably because it is confidential information), but just review the query.
You can just execute a query like this before to mock some mailaddresses in the data.
```
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX schema: <http://schema.org/>
INSERT {
GRAPH <http://mu.semte.ch/graphs/public> {
?bestuurseenheid …
```
=> LMB-883 add migration to migrate contact info

config/form-content/mandataris-edit/form.ttl, config/form-content/persoon/form.ttl
Change the datetime displaytypes to the new custom dateInput displayType. All bestuursperiode validations should already be in place in the ttl so nothing to change there.
1. Kill form-content 
2. Start the app
3. Follow the test steps in the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/351
=> LMB-856: Use custom dateInput compoinent instead of displaytype datetime

config/migrations/2024/20241017085951-fix-bindingStart-dates.sparql
Fix bestuursorganen in de tijd which have wrong or no bindingStart.
My local data was okay, but for some reason the fake bestuursorganen in de tijd on test did not have a bindingStart. So it is difficult to test this locally, but you can check if the migration works and does not update the bindingStart of other bestuursorganen in de tijd.
=> add migration to fix end dates bestuursorganen in tijd 2024-2030

config/migrations/2024/20240910102800-legislation-2025/20241022093421-new-installatievergaderingen-ocmw.sparql
OCMW's did not have an IV, this made sense because we do the IV in the corresponding municipality. However if we want to disable certain modules during the preparation of the legislature, it makes sense to have this relation as well.
Run the migration and check if OCMW's now have IV's as well.
- https://github.com/lblod/mandataris-service/pull/54
=> add iv to ocmw's

config/migrations/2024/20241023131900-add-identifiers-to-person-graph.sparql
add identifiers to person graph if missing
get production data and see that some identifiers were in other graphs than where the persons now resided (people moved to a different commune)
After this migration the identifiers should also be visible to the new commune
=> add identifiers to person graph if missing

config/ldes-delta-pusher/initialization.ts, config/ldes-delta-pusher/ldes-instances.ts, config/ldes-delta-pusher/publisher.ts, config/resources/repository.lisp
This fixes the issues with the persoon prefix that should be https but is defined as http in our application.
We can just handle this by adding the predicates and type values with both http and https on the ldes.
Run the initial sync of the ldes and notice that the predicates on persoon are defined both as http and https. Also notice that the type of geboorte is defined as both http and https.
Also notice that other types are still present in the initial dump to ldes.
Then update a person and see that the same holds for Person and Geboorte instances. 
Update another type, like Mandataris and see that it is also still written to the right LDES streams
=> resolve prefix issues on ldes level

config/migrations/2024/20241023164310-add-geboortes-to-person-graph.sparql
Description
add geboortes to person graph if missing
How to test
get production data and see that some geboortes were in other graphs than where the persons now resided (people moved to a different commune)
After this migration the geboortes should also be visible to the new commune
=> add geboortes to person graph if missing 

config/migrations/2024/20241024092700-make-new-mandatarisses-draft.sparql
make new mandataris instances draft and remove their fractions which are incomplete.
Get a dump from loket with the mandatarisses that have been created for the next period already. Run this migration and see that their publication status is now draft and their fractions have been removed.
=> make new mandataris instances draft and remove their fractions which are incomplete

config/migrations/2024/20241025161900-fix-person-names.sparql
fix some person names as requested by Nele
this query selects all information on the uris mentioned by the ticket
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?person ?p ?o WHERE {
VALUES ?person {
<http://data.lblod.info/id/personen/5D9DEE71A3ACB600080000ED>
<http://data.lblod.info/id/personen/5D9DED7DA3ACB600080000E8>
<http://data.lblod.info/id/personen/5D9DE927A3ACB600080000D9>
<http://data.lblod.info/id/personen/5D9DEB69A3ACB600080000E0>
<http://data.lblod.info/id/persoon/4d5d6354-162d-4b4a-b4ee-5a317fa0bfd2>
<http://data.lblod.info/id/personen/5D9DF2FCA3ACB600080000FA>
<http://data.lblod.info/id/persoon/7fa8a756-7d53-4ebb-b821-55c2b2e153a4>
<http://data.lblod.info/id/persoon/4ff24ac1-3e24-4f70-8ada-2e92c05382ba> …
```
=> fix some person names as requested by Nele

config/migrations/2024/20241028084700-expose-verkiezingen-to-ocmw/20241028084700-copy-verkiezingen.sparql, config/migrations/2024/20241028084700-expose-verkiezingen-to-ocmw/20241028084701-copy-verkiezing-data.sparql, config/migrations/2024/20241028084700-expose-verkiezingen-to-ocmw/20241028084702-copy-kieslijsten.sparql, config/migrations/2024/20241028084700-expose-verkiezingen-to-ocmw/20241028084703-copy-results.sparql, config/migrations/2024/20241028084700-expose-verkiezingen-to-ocmw/20241028084704-copy-persons.sparql, config/migrations/2024/20241028084700-expose-verkiezingen-to-ocmw/20241028084705-copy-person-data.sparql
expose election data to ocmw as they can only pick people who have been elected
using https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/402, go to an ocmw of the new period and add mandataris instances after closing the IV prep. You should see person instances to select
=> expose election data to ocmw as they can only pick people who have been elected

config/dispatcher/dispatcher.ex, docker-compose.yml
redirect delete of fraction to mandataris service
go to the frontend and delete a fraction (e.g. in the installatievergadering). a tombstone will be erected for it immediately.
- https://github.com/lblod/mandataris-service/pull/62
=> redirect delete of fraction to mandataris service

config/form-content/persoon/form.ttl
We want the gender to be automatically filled in. We created a component for this that we registered in the frontend.
- Use the app togheter with the frontend to use the new displaytype
- restart the form-content service for this
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/409
=> lmb-: use gender selector display type

config/ldes-delta-pusher/ldes-instances.ts, config/migrations/2024/20241113104300-fix-duplicate-modified.sparql, config/migrations/2024/20241113104301-fix-duplicate-deleted.sparql, docker-compose.yml
add healingFilter to tombstones so it doesn't add tombstones on ldes for things that still exist in other graphs
also remove duplicate modified and deleted dates, keep the most recent one.
- fetch the test db and ldes, restore it locally
- set the ldes delta pusher to the version in the linked pr
- have the ldes heal itself
- have the ldes heal itself again and notice that there is nothing to be healed
- https://github.com/redpencilio/ldes-delta-pusher-service/pull/12
=> fix tombstone modified and deleted dates, don't try to create superflous tombstones

config/cl-authorization/config.lisp
The besluiten-consumed graph should be accessible for authenticated users.
Check code and see linked PR.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/429/files
=> make besluiten-consumed graph accessible for authenticated users

docker-compose.dev.yml
Profile removed so it runs standard when developing. Last change to the service was 2 months ago
Run drc up -d and it should spin up the service :)
=> feat: remove nodebug profile from `form-content` service in dev compose

config/migrations/2024/20241122140200-fix-tombstone-modifieds.sparql, config/modified/config.ts
some tombstones didn't get a modified date. Use their deleted time as a modified date
- Run the migration and see that you have no tombstones without a modified date
- run the old mandataris service (from before this PR https://github.com/lblod/mandataris-service/pull/71) and delete a mandataris. Your tombstone will now have a modified date again (but we should still keep the linked pr so that this extra step is not necessary)
=> fix missing modified on tombstones

config/ldes-delta-pusher/ldes-instances.ts, config/migrations/2024/20241125151000-purge-duplicate-modifieds.sparql
purge duplicate modifieds, keep oldest. don't heal tombstones if they already exist, we don't really care about their modified dates
load prod db and ldes feed, heal it, see there are barely any changes to be healed. heal the stream and see the outstanding changes are no longer there
=> fix tombstones missing in GN after loading ldes, weren't auto-healed

config/migrations/2024/20241126091000-fix-blankenberge-fractions.sparql
blankenberge has created fractions in loket but then also created fractions in lmb. These have to be deduplicated and cleaned up.
- start from a prod dump
- open the frontend with ember dev tools and see that there are 10 fractions loaded when opening the iv in blankenberge
- run this migration
- kill resource and cache
- up resource and cache
- open the frontend with ember dev tools and see that there are only 5 fractions loaded when opening the iv in blankenberge
- see that all mandatarisses in the iv still have a fraction
=> fix blankenberge fractions

config/ldes-delta-pusher/handle-membership-type.ts, config/migrations/2024/20241120124400-generic-prefix-http.sparql
Sometimes a triple has a generiek prefix uri with https, this should always be http except for the ldes data
- Get one triple with the generiekHttps prefix an see if a duplicate has been added with the generiek Http prefix
LDES constructs these
```bash
ldes-delta-pusher-1  | DEBUG: [abb] Publishing data for subject http://data.lblod.info/id/lidmaatschappen/5C3DC54257753A000900022B:
ldes-delta-pusher-1  | <http://data.lblod.info/id/lidmaatschappen/5C3DC54257753A000900022B> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Membership> .
...
ldes-delta-pusher-1  | <http://data.lblod.info/id/tijdsintervallen/2c59e367-a0be-440e-8e75-0767c19e01ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/terms/PeriodOfTime> .
ldes-delta-pusher-1  | …
```
=> Lmb 1072 | Use generiek prefix with HTTP in our app

config/migrations/2024/20241129081026-fix-incorrect-names.sparql
Fix wrong names verkiezingsresultaten from helpdesk. 
This PR only fixes the exact ones, there are also issues with capitilization, but that is still ongoing.
Just check if you can run the migration and whether e.g "boer Jan" is still used in the database.
=> LMB-1100 fix incorrect names

config/migrations/2024/20241128161131-move-people-created-in-bcsd.sparql
There is new logic that creates people created in the BCSD in the IV in the OCMW graph as well. However some people were created before this change, this migration moves them over.
Check if the migration runs. If you want to you can check if there exist people that exist in the gemeente, linked to a ocmw orgaan and don't exist in their corresponding ocmw graph. 
- https://github.com/lblod/mandataris-service/pull/73
=> LMB-1074 Copy people created in bcsd to ocmw graph

config/migrations/2024/20241129102606-fix-capitilisation-names.sparql
There were a few names that were in all capitals, these migrations should fix this.
Check if the migrations run.
If you want you can then check if there still exist people with names in all capitals. Something like this:
```
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT COUNT(DISTINCT ?uri) as ?count
WHERE {
GRAPH ?g {
?uri a person:Person ;
persoon:gebruikteVoornaam ?name .
FILTER (isLiteral(?name) && STRLEN(?name) != 0 && STR(?name) = UCASE(STR(?name)))
}
?g ext:ownedBy ?someone .
}
```
=> LMB-1117 fix capitilisation in names

config/migrations/2024/20241127152018-remove-duplicate-organen.sparql
Remove duplicate organen, these were added in a faulty migration to:
- Beernem
- Kruisem
- Opwijk
- Moorslede
- Dentergem
- Kortenberg
Best to add a mandataris to the two instances of the same orgaan. Then you can run the migrations. 
Best to restart cache and resources after the migration, then you should see that these duplicate organs are gone and that both mandatarissen you added before should be added to one organ.
=> LMB-1091 remove duplicate organen

config/form-content/bestuursorgaan/form.ttl, config/migrations/2024/20241202200400-fix-missing-classification-codes.sparql
Merchtem managed to create a custom organ and then clear its classification. This brought the system in an unexpected state and suddenly they couldn't edit the fractions of mandatarises (true story).
See that merksem now has their custom org back and that they can edit their mandataris instances again.
=> disallow setting classification code to nothing, fix missing classification code organs

config/migrations/2024/20241204134500-delete-mandatarissen-wrong-period.sparql
> [!WARNING]
> don't merge until we checked with the municipalities that did not actively request this.
The mandatarissen are deleted by uri. The query used to fetch them was:
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT distinct ?mandataris ?label ?labelE ?firstname ?name WHERE {
?mandataris a mandaat:Mandataris .
?mandataris mandaat:start ?start.
FILTER(?start > …
```
=> delete mandatarissen entered in wrong period with tombstones

config/migrations/2024/20241205111430-kortenaken-gr-voorzitter-koen.sparql
Kim is removed from the mandataris and Koen is added to that same mandataris
1. see IV Kortenaken Gemeenteraad voorzitter (Kim)
2. Run migration with prod dump
3. Remove resource and cache (drc rm , drc up)
4. Voorzitter should be Koen
=> lmb-1146: migration to remove Kim as voorzitter and set it to Koen

config/migrations/2024/20241204163100-add-ovo-and-kbo-to-borsbbeek.sparql
Migration that adds the ovo and kbo number for borsbeek
Query should include the kbo and ovo number like it does for the commented bestuurseenheid
```
SELECT *
WHERE {
GRAPH ?g {
VALUES ?b {
<http://data.lblod.info/id/bestuurseenheden/4b44e6f1-113b-4692-b149-44a889b215f2>  # Borsbeek
}
?b a besluit:Bestuurseenheid.
?b ?p ?o.
}
}
```
=> lmb-1142: add migration to add the ovo and kbo number to Borsbeek

config/migrations/2024/20241211095143-update-end-date-of-bestuursorganen.sparql
We got email from remicon that they expect a different end date 2025-01-01 is wrong => change it to 2024-12-2
Migration runs on prod data. There test query should only return one entree
```
#+begin_src sparql :url "http://localhost:8890/sparql" :format text/csv
SELECT ?orgaanTijdspecialisatie ?orgaanTijdspecialisatieEinde ?orgaanTijdspecialisatieStart
WHERE {
GRAPH ?g {
BIND ("""2024-12-09"""^^<http://www.w3.org/2001/XMLSchema#date> AS ?vergaderingDatum)
?orgaanTijdspecialisatie <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/888aa938e198341244135e14d2faaf7efdedb126c4e245c3c4db6caaf87d71aa> ;
<http://data.vlaanderen.be/ns/mandaat#bindingStart> ?orgaanTijdspecialisatieStart.
}
OPTIONAL {?orgaanTijdspecialisatie …
```
=> Lmb 1180 | fix end date organen in tijd 2024-12-02

config/migrations/2024/20241213110257-kortenaken-failing-person.sparql
When accessing the person Kim Vandepoel in OCMW you got an error page.
A migration that needed to add gemeenteraadslid to Kim also added this in the OCMW, which created this error.
Check if migration runs and if you can now access this person in the OCMW.
=> LMB-1185 Fix failing person in OCMW Kortenaken

docker-compose.yml
Fixed a cron pattern in the delta consumer. This service was down on dev and test. 
It is fine on prod, because there the cron pattern is overwritten in the `docker-compose.override.yml`
If you ran the delta-consumer before, without override, the service would crash, because it is not a valid cron pattern. Now with this PR it should be fine.
=> LMB-1187 fixed cron pattern delta consumer

config/migrations/2024/20241205154800-link-not-linked-mandatarissen-from-past-1.sparql, config/migrations/2024/20241205154800-link-not-linked-mandatarissen-from-past-2.sparql, config/migrations/2024/20241205154800-link-not-linked-mandatarissen-from-past-3.sparql, config/migrations/2024/20241205154800-link-not-linked-mandatarissen-from-past-4.sparql, config/migrations/2024/20241205154800-link-not-linked-mandatarissen-from-past-5.sparql, config/migrations/2024/20241205154800-link-not-linked-mandatarissen-from-past.sparql
Its possible that some mandatarissen are not linked in the current bestuursperiode as this is something we did later. We have written a insert query that will link the mandatarissen that should to each other.
Run the query as a `SELECT`  without the `FILTER NOT EXISTS`  (bnut with the union) and see the `COUNT` of what it returns (136 +-). After running that one run the query from this PR. This should make the count of the first query zero.
NOTE: this query can take some time
=> lmb-1111 | create query that will link the non linked mandatarissen

config/migrations/2024/20241216140500-clean-up-duplicate-membershipts.sparql
we got some duplicate memberships from loket it seems. This removes them.
go to riemst, see that dirk doesn't have a cd&v fractie linked
=> clean up duplicate memberships

config/migrations/2024/20250109090600-fix-duplicate-person-uri.sparql
Loket had two person uris for this person, one of them had a space in their first name. We merge them and keep a sameAs between them.
Cevi ran this query (minor modifications):
```
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#> 
PREFIX org: <http://www.w3.org/ns/org#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
SELECT DISTINCT ?persoonUri ?achternaam ?naam
WHERE {{ 
VALUES ?achternaam {
"Van Loo"
}
?orgaan mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/4d4541a07717e84e183b13c4400212d9dd708c2c470b0854e5631ef278d8dbf7> ; 
org:hasPost ?mandaat . 
?mandataris org:holds ?mandaat ; 
mandaat:isBestuurlijkeAliasVan ?persoonUri . 
?persoonUri …
```
=> fix duplicate person uri

config/migrations/2025/20250113160300-fix-cdnv-tesssenderlo-ham.sparql
fix name cd&v tessenderlo ham
run this and restart resources and cache, see that the name of cd&v tessenderlo ham was updated from cd&v ham
=> fix name cd&v tessenderlo ham

config/migrations/2025/20250116130100-fix-antwerpen-unfinished-prep.sparql
This adds the persons for the members of municipality council, rmw, college and vb. It removes the incomplete members of bcsd
Verify that there are no gaps in the prepare legislature section and that the people in the ticket have the right rank
Other changes will be done using correct mistakes/regular interface
=> fix unfinished prep of next legislature for antwerpen

config/ldes-delta-pusher/handle-decision-type.ts, config/ldes-delta-pusher/handle-mandataris-type.ts, config/ldes-delta-pusher/handle-membership-type.ts, config/ldes-delta-pusher/handle-regular-types.ts, config/ldes-delta-pusher/handle-types-util.ts, config/ldes-delta-pusher/publisher.ts
To prevent sparql injection we need to escape all user input value with the mu package sparqlEscape methods
You can write the initial ldes-stream and see if all get parsed correctly in the output files 
- https://github.com/lblod/mandataris-service/pull/86
- https://github.com/lblod/form-content-service/pull/70
=> lmb-1055 | escape all "user" input date in the ttl

config/cl-authorization/config.lisp, config/form-content/mandataris-edit/form.ttl, config/form-content/persoon/form.ttl, config/migrations/2025/20250106141000-create-form-field-library.sparql, config/migrations/2025/20250107114000-add-display-types.sparql, config/resources/external-mandaat.lisp
Allow complex paths in library fields. Example: datum van overlijden
Add the the field to a form, e.g. the correct mistakes form of a mandataris. See that the generators do their work and that the field is added along the path persoon:heeftOverlijden / persoon:datum
- https://github.com/lblod/form-content-service/pull/67
=> complex paths in library fields

config/migrations/2025/20250130113602-update-fractie-districtsburgemeester-hoboken.sparql
Migration which adds a fractie to the districtsburgemeester of Hoboken.
You might need to get a prod dump, not sure how recent this burgemeester data is. After running the migration you should see that the districtsburgemeester of Hoboken of the current bestuursperiode now has a fractie and that it no longer fails if you try to edit the dates of this burgemeester.
=> LMB-1339 migration to add fractie to districtsburgemeester Hoboken

config/migrations/2025/20250204162300-correctie-rangorde-boechout.sparql
this removes the extra mandatarissen created in boechout so we can fix their rangorde properly
go to boechout, there should only be bekrachtigde mandatarissen and the rangorde should be consistent
=> fix gr and rmw boechout

config/migrations/2025/20251102164000-add-hide-iv-triple-to-eenheden.sparql, config/resources/external-besluit.lisp, config/resources/verkiezingen.lisp
We want to add a temporary triple to the bestuurseenheden to hide the legislatuur module `ext:voorbereidingVerborgen`
- There should be **551** bestuurseenheden with this triple
```sparql
SELECT COUNT(DISTINCT ?iv) AS ?count
WHERE {
GRAPH ?g {
?iv lmb:hasStatus <http://data.lblod.info/id/concept/InstallatievergaderingStatus/c9fc3292-1576-4a82-8dcd-60795e22131f> . # Behandeld
}
?g ext:ownedBy ?someone .
}
```
- There should still remain **53** bestuurseenheden without this triple
```sparql
PREFIX …
```
=> lmb-1168 | add query that adds  the hide triple to the bestuurseenheid

config/migrations/2025/20250212113600-fix-too-many-bekrachtigingen.sparql
removes auto bekrachtigingen created:
- in previous periods
- for mandatarissen that are not the first in their organ
query used to find bekrachtigd but not first:
```
SELECT distinct ?mandataris WHERE {
?besluit mandaat:bekrachtigtAanstellingVan ?mandataris .
GRAPH ?g {
?mandataris org:holds ?mandaat.
?mandataris mandaat:start ?start.
?otherMandataris org:holds ?mandaat.
?otherMandataris mandaat:start ?startEarlier.
}
?g ext:ownedBy ?someone.
FILTER(?startEarlier < ?start)
} 
```
verify that there are no bekrachtigd mandatarissen in previous period: 
```
PREFIX lmb: …
```
=> fix too many bekrachtigingen created

config/migrations/2025/20250226135551-fix-dates-reverse-order.sparql
Few dates where in reverse order. This should fix that.
Check if the migration runs. If you want to check if there are more dates that are in reverse order, this query can help:
```
SELECT DISTINCT * WHERE {
?s persoon:datum ?date.
FILTER(SUBSTR(STR(?date), 3, 1) = "-")
}
```
=> LMB-1438 fix dates that were in reverse order

config/migrations/2025/20250303125600-remove-unconnected-mandatarissen.sparql
removes mandatarissen that didn't have a person connected.
run this query to validate before and after:
```sparql
SELECT * WHERE {
GRAPH ?g {
?s a mandaat:Mandataris.
FILTER NOT EXISTS {
?s mandaat:isBestuurlijkeAliasVan ?persoon.
?persoon a ?thing.
}
}
?g ext:ownedBy ?someone.
?someone skos:prefLabel ?label.
}
```
=> remove unconnected mandatarissen

docker-compose.yml
Add timezone to mandataris service. This should fix issues with downloading mandatarissen.
When you download a csv of mandatarissen, the start dates should now be correct. Before these dates were one day of because of the timezones.
- https://github.com/lblod/mandataris-service/pull/110
=> LMB-1444 add timezone to mandataris service

config/migrations/2025/20250314075629-fix-incorrect-mandataris-uris.sparql
There were some mandatarissen with weird uris. This migration replaces those uris and adds a tombstone for the old uris.
Check if the migration runs and the following query should return no results:
```
SELECT COUNT(DISTINCT ?mandataris) AS ?count
WHERE {
GRAPH ?g {
?mandataris a mandaat:Mandataris .
FILTER(!STRSTARTS(STR(?mandataris), "http://data.lblod.info/id/mandatarissen/"))
}
?g ext:ownedBy ?bestuurseenheid .
}
```
=> LMB-1432 Fix incorrect mandataris uris

config/migrations/2025/20250311092100-remove-all-emails-from-outbox.sparql, config/migrations/2025/20250311092100-remove-all-emails-from-to-send-folder.sparql, config/resources/external-mandaat.lisp, docker-compose.yml
We want to change the logic for notifications. Before 10 days after effectief (niet-bekrachtigd publication status) a notification was send (this was disabled). We do want these notifications but when a mandataris is active for more than 10 days. (start date + 10 days  > today)
- see mandataris service
- [mandataris](https://github.com/lblod/mandataris-service/pull/108)
- [frontend](https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/515)
=> lmb-1428 | Notification for mandataris that is more than 10 days active

docker-compose.yml
the heap size of the sparql parser needs to be bumped because without this, queries that modify a lot of triples can sometimes cause out-of-memory errors
does the app still run?
=> increase lisp heap size for sparql-parser

docker-compose.yml
- virtuoso from `redpencil/virtuoso:1.2.0-rc.1` to `redpencil/virtuoso:1.3.0-rc.1`
- sparql-parser (database) from `semtech/sparql-parser:0.0.12` to `semtech/sparql-parser:0.0.14`
1. create checkpoint in virtuoso `drc exec -ti virtuoso isql-v` => `checkpoint;`
2. copy the `/data/db` folder `APP-LMB> cp -r ./data ./data-before-virtuoso-bump`
3. Follow these steps for upgrading https://github.com/redpencilio/docker-virtuoso/?tab=readme-ov-file#upgrading
- /
=> LMB-1238,1462 |Bump virutoso and sparql parser

config/reports/helpers.js, config/reports/shacl-report.js
improvements to report generation service:
- allow running reports on start for debugging
- run batches of eenheden at nightly run, based on which has the oldest report (batch size 50 by default)
- fix old report deletion
run the reports on start with a batch size of 3, see that three eenheden are processed and the system then stops.
run it again and see 3 new eenheden are processed
=> better report generation

config/migrations/2025/20250331084700-add-display-types.sparql
We need 2 more custom display types so the user can select a single or multiple concept-schemes
Run the migrations and test with the frontend to see if it is possible to add fields with concept-scheme selection to the form.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/528
- https://github.com/lblod/form-content-service/pull/77
=> LMB-1500 | Migration to add concept-scheme to custom-display-types

config/migrations/2025/20250411151500-prep-op-consume/20250411151500-delete-bestuurseenheden.sparql, config/migrations/2025/20250411151500-prep-op-consume/20250411151501-delete-bestuursorganen.sparql, config/migrations/2025/20250411151500-prep-op-consume/20250411151502-delete-mandaten.sparql, config/op-consumer/mapping/queries/README.md, config/op-consumer/mapping/queries/op2dl/identifier/identifier-kbo.rq, config/op-consumer/mapping/queries/op2dl/identifier/identifier-ovo.rq, config/op-consumer/mapping/queries/op2dl/mapping/bestuursorgaanLabel.sparql, config/op-consumer/mapping/queries/op2dl/mapping/classification.sparql, config/op-consumer/mapping/queries/op2dl/mapping/ext-bestuurseenheid-classificatie-code.sparql, config/op-consumer/mapping/queries/op2dl/mapping/ext-representatief-orgaan-code.sparql, config/op-consumer/mapping/queries/op2dl/mapping/isTijdspecialisatieVan.sparql, config/op-consumer/mapping/queries/op2dl/pass/pass-all-properties.sparql, config/op-consumer/mapping/queries/op2dl/pass/pass-without-identifier-or-classsification.sparql, config/op-consumer/mapping/queries/op2dl/pass/pass-without-lmb-properties.sparql, config/resources/external-besluit.lisp, docker-compose.dev.yml, docker-compose.yml
add op public consumer, keep some predicates on our end as not yet implemented in op
- update mandataris to match linked pr
- start the stack and let migrations run but don't start the op-public-consumer yet
- once migrations are ready, start op-public-consumer, this will run for a while (~10min)
- you're now up to date with op regarding the op data
- check if the main paths in the app still work (add/edit/update mandataris, reorder rangorde, ...) 
- https://github.com/lblod/mandataris-service/pull/113
=> consume op data

config/ldes-delta-pusher/ldes-instances.ts
this publishes beleidsdomein codes (because users can create their own beleidsdomeincodes)
add a beleidsdomein code, see that it is published in all streams
you also will want to check that you can republish all existing codes using the republish-ldes-data project script
to do that, run this query to get all codes:
```
CONSTRUCT {
?s a <http://mu.semte.ch/vocabularies/ext/BeleidsdomeinCode>
}WHERE {
?s a <http://mu.semte.ch/vocabularies/ext/BeleidsdomeinCode>
}
```
add them to scripts/ldes-republish/data.ttl
then run `mu script project-scripts ldes-republish`
this will create about 720 page in each ldes feed containing the missing items immediately.
(this info was also added to a deploy task in jira so it happens in prod)
you will need the fixes here to be able to add beleidsdomeincodes …
=> publish beleidsdomein codes again

config/ldes-delta-pusher/dispatch.ts, config/ldes-delta-pusher/handle-tombstone-type.ts, config/ldes-delta-pusher/ldes-instances.ts
Now tombstones are being added to the ldes stream even if the type is not published on that stream. Nothing big but we do not want to add these tombstones to the streams.
1. Comment an entity type from ONE stream in the `ldes-instances.ts` file (my example is a mandataris as i can easely remove that one)
2. Restart your app (or only the ldes-delta-pusher)
3. Remove through the frontend that type of entity
4. Follow the logs of the ldes-delta-pusher and the stream you commented the type in should not publish the tombstone
The log should something like this (i removed some predicates from this)
```bash
ldes-delta-pusher-1  | DEBUG: [abb] Publishing data for subject http://data.lblod.info/id/mandatarissen/2ad2a6d4-5c03-42ae-82ff-f64da6e71d91:
ldes-delta-pusher-1  | 
ldes-delta-pusher-1  | …
```
=> LMB-1024 | Only publish tombstones of types that we add to the stream

config/cl-authorization/config.lisp, config/migrations/2025/20250709083400-add-url-as-custom-field.sparql
Adding a new displaytype to thte database so we can add a url field to our custom forms. Note that this field has a validation added to it wihtout a path. This is handled in the form content service.
1. run the migrations
2. Make sure the cache was cleared and test with togheter with the other PR's
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/593
- https://github.com/lblod/form-content-service/pull/88
=> LMB-1681 | Custom url field

config/form-content/bestuursorgaan-extra-info/form.ttl
We want a form extension for a bestuursorgaan so organen can also add extra info. 
1. Does the form include all the fields?
2. Run together with the frontend (make sure to restart your local form-content service to retrieve the form)
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/596
=> lmb-1679: create form extension for bestuursorganen

config/migrations/2025/20250718135200-update-aantallen-schepen-lidvb.sparql
We need to update the aantallen for Antwerpen, Brecht and Lebbeke.  Schepen & Lid Vast Bureau.
1. Check the current values (Lebbeke is already up to date?)
1.1 Can also check with the migration query but with a select
```sparql
SELECT DISTINCT ?bestuurseenheid ?eenheid ?houders ?minHouders ?newHouders
````
3. Run the migration => values should equal to the new values
4. Check another period it should not been affected by the migration
**Current aantallen**
```md
| eenheid   | houders | minHouders | newHouders |
+-----------+---------+------------+------------|
| Antwerpen |       9 |          9 |         11 | Gemeente
| Antwerpen |       9 |          9 |         11 | OCMW
| Brecht    |       5 |          5 |          6 | Gemeente
| Brecht    |       5 |          5 |          6 | OCMW
| …
```
=> lmb-1687: migration that will update schepen and vast bureau aantallen

config/migrations/2025/20250731132100-fix-link-to-besluit-copied.sparql
fix link to besluit copied
use the broken version of mandataris service to change rangordes for mandataris with link to besluit
run this migration
restart resource and cache
refresh the page
see that the link to besluit is gone
- https://github.com/lblod/mandataris-service/pull/125
=> fix link to besluit copied

config/migrations/2025/20250808100000-expose-verkiezingen-to-ocmw/20250808100001-copy-verkiezingen.sparql, config/migrations/2025/20250808100000-expose-verkiezingen-to-ocmw/20250808100002-copy-verkiezing-data.sparql, config/migrations/2025/20250808100000-expose-verkiezingen-to-ocmw/20250808100003-copy-kieslijsten.sparql, config/migrations/2025/20250808100000-expose-verkiezingen-to-ocmw/20250808100004-copy-results.sparql, config/migrations/2025/20250808100000-expose-verkiezingen-to-ocmw/20250808100005-copy-persons.sparql, config/migrations/2025/20250808100000-expose-verkiezingen-to-ocmw/20250808100006-copy-person-data.sparql
Some persons are not linked to the election data for Herstappe and Lo-Reninge.
Test with this query  first
```sparql
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
#SELECT COUNT(DISTINCT ?person) AS ?count
SELECT DISTINCT ?person ?fName ?lName ?verkiezingsresultaat ?bestuursorgaanLabel
WHERE {
VALUES ?gemeenteraadRole { …
```
=> lmb-1297 | persons without election data

config/migrations/2025/20250728083100-cleanup-mandataris-start-einde-xsd-date-datatype/20250728083100-mandataris-start.sparql, config/migrations/2025/20250728083100-cleanup-mandataris-start-einde-xsd-date-datatype/20250728083101-mandataris-einde.sparql
The domain says that the datatype of `mandaat:start` and `mandaat:einde` should be `xsd:dateTime` and not `xsd:Date`.
1. create the migrations  => directly correct the time to be correctly (start and end -of day)
2. Have a look at the non mandataris types and why they get the xsd:date datatype
1. Check the count of xsd:date datatypes for a mandataris
```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?type ?predicate COUNT(?object) AS ?count
WHERE {
GRAPH ?g {
VALUES ?predicate {
mandaat:start
mandaat:einde
}
?subject a ?type .
?subject ?predicate ?object .
FILTER(datatype(?object) = xsd:date)
}
} GROUP BY ?predicate …
```
=> lmb-1712 | Fix the xsd:date to be xsd:dateTime for mandataris start and einde

config/cl-authorization/config.lisp
Impersonation didn't work on PROD, so we could not use the admin functionality there. Updated the authorization config  so an admin can access all organizational data. (same as app-digitaal-loket) but our org is named organization
- change it in the test server ;p
=> LMB-1779 | add authorization rule for logged-in-or-impersonating
