config/dispatcher/dispatcher.ex
config/form-content/mandataris/form.ttl
docker-compose.dev.yml
docker-compose.yml

also stops the jobs controller from restarting in dev

add form content service

---

config/dispatcher/dispatcher.ex

Removed resources from dispatcher that were no longer in the resource files. 
also grouped dispatcher links that belong together -> Still not perfect, but at least it now resembles the resource files.

clean up dispatcher

---

config/form-content/bestuursorgaan/form.ttl
config/form-content/contactpunt/form.ttl
config/form-content/fractie/form.ttl
config/form-content/mandaat/form.ttl
config/form-content/mandataris/form.ttl
config/form-content/persoon/form.ttl

Add labels to the form definition. With this label, form instances can be coupled to a form definition.

Form instances

---

config/authorization/config.ex
config/form-content/persoon/form.ttl

fix authorization acces some forms

---

config/authorization/config.ex

This reverts commit e02db1ea5e3b03941d87317df2350cf85dac066d.

Revert "prevent double write person resources"

---

config/form-content/test/form.ttl

Simple test form for type selector component.

Type selector

---

config/form-content/bestuursorgaan/form.ttl
config/form-content/contactinfo/form.ttl
config/form-content/contactpunt/form.ttl
config/form-content/edit-mandataris-einde/form.ttl
config/form-content/edit-mandataris/form.ttl
config/form-content/fractie/form.ttl
config/form-content/functionaris-edit/form.ttl
config/form-content/functionaris-new/form.ttl
config/form-content/mandaat/form.ttl
config/form-content/mandataris-hidden-persoon-new/form.ttl
config/form-content/mandataris-new/form.ttl
config/form-content/persoon/form.ttl
config/form-content/test/form.ttl

The [Added human-readable URI and mu:uuid to all forms](https://github.com/lblod/app-lokaal-mandatenbeheer/commit/3fbc00c5db0af87d96745939864836e153aecd70) commit is the important one, you'll probably want to look at that one first.
The second commit is purely formatting changes with no functional impact

Assign Proper Form URIs and UUIDs

---

config/resources/external-mandaat.lisp

add inverse relation mandataris - mandaat

LMB-120 Bestuursorgaan page

---

config/form-content/mandataris-new/form.ttl
config/resources/external-mandaat.lisp

Added ext:isDraft to resources and mandataris-new form

Mandataris draft

---

config/form-content/fractie/form.ttl

The validation on Fractie naam serves as an example of the validations that will be added in the future.

Add required constraint to fractie naam

---

config/form-content/bestuursorgaan/form.ttl
config/migrations/2024/20240405074800-decretaal-bestuursorgaan-codes-reorganize.sparql

split bestuursorgaan codes

---

config/migrations/2024/20240409162518-move-mandaat-to-bestuursorgaan-graph.sparql

LMB-179
This query should returning no results
```sparql
SELECT * where {
GRAPH <http://mu.semte.ch/graphs/public> {
?mandaat a mandaat:Mandaat .
?mandaat  ?predicate ?object . 
}
} LIMIT 1000 
```

LMB-179: Migration to move the mandaat to bestuursorgaan graph

---

config/cl-authorization/config.lisp
docker-compose.dev.yml
docker-compose.mac.yml

We're keeping the old configuration around for use on the dev/test server for now as we don't want to expose our partners to the potential issues with a new mu-auth.

New mu-authorization configuration

---

.github/pull_request_template.md

Create a template file to everyone knows what the implementation does

LMB-405: add PR template

---

.github/pull_request_template.md

_Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues._
Remove the link any related issues to prevent developers linking to jira tickets that are in a private workspace
Not needed.

Remove link issues in PR template

---

docker-compose.yml

Tiny pr to bump the acm/idm service so we can use JWK 
You can't right now. Just check if the docker compose still runs

bump acm idm service

---

config/resources/external-mandaat.lisp
config/resources/verkiezingen.lisp

Update resources to link kieslijst to fractie.
See frontend PR.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/196

link kandidatenlijst to fractie

---

config/form-content/mandataris-edit/form.ttl
config/resources/external-mandaat.lisp

Add new property to mandataris  for linking besluit to mandataris
Run te backend with the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/209

LMB- 296: Mandataris has a link to besluit

---

config/authorization/config.ex
config/cl-authorization/config.lisp
config/dispatcher/dispatcher.ex
config/resources/domain.lisp
config/resources/system-notification.lisp
config/resources/user.lisp

Create a resource for system notifications. These system notifications are attached to a 'Gebruiker'
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/207

Lmb 388/system notification resource

---

config/dispatcher/dispatcher.ex
config/migrations/local/20240507135000-fake-kalliope-vendor.sparql
docker-compose.yml

add config for burgemeester benoeming, add fake kalliope vendor key, bump file service
to be tested in tandem with the linked pr, see that pr for steps on how to test
- https://github.com/lblod/mandataris-service/pull/2

add burgemeester benoemingen api

---

config/form-content/mandataris-edit/form.ttl
config/form-content/mandataris-new/form.ttl

use custom fields in mandataris form for limited fields
See the linked frontend pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/214

use custom fields in mandataris form for limited fields

---

config/dispatcher/dispatcher.ex

add dispatcher rule for installatievergadering

add dispatcher rule for installatievergadering

---

docker-compose.yml

Bump versions for updating test and dev server.

bump versions

---

docker-compose.yml

Bump mandataris service to fix besluiten 500 API issue
Click through the app to see if everything still works (especially mandataris related functionality)

Bump mandataris service

---

docker-compose.yml

bump mandataris-service

---

docker-compose.yml

add volume for the files holding mayor ratifications
ratify/reject a mayor, see that the file is added to the data folder.

add volume for the files holding mayor ratifications

---

config/delta/decisions.js
config/delta/rules.js

Adding the delta rule so we can process all the consumed mandatees-decisions in our LMB services
Run it togheter with the mandataris service and mandatees-decisions app. See test in other PR.
- Mandataris Service | https://github.com/lblod/mandataris-service/pull/17

LMB-519: Delta rule for mandatees-decisions

---

config/migrations/2024/20240703001144-tmp-ocmw-bestuursorganen.sparql

Just a comment so we know why we did this and why it is fine (also autoformatting)

clarify why adding the mandataris instances of the fake ocmw organs to ldes is fine

---

docker-compose.yml

This bumps the fragmentation producer so we can get around a bug that was fixed in that version

bump fragmentation producer to 0.4.1

---

scripts/loket-to-lmb-transform/Dockerfile
scripts/loket-to-lmb-transform/anonymize.ts
scripts/loket-to-lmb-transform/app.ts
scripts/loket-to-lmb-transform/docker-compose.anonymize.yml
scripts/loket-to-lmb-transform/docker-compose.export.yml
scripts/loket-to-lmb-transform/docker-compose.transform.yml

Adds an additional script option to anonymize the loket data (removes gender, birth date, nationality, rrn)
Run the script on production data. Verify that you can't identify persons anymore (names are fine as they are already public)

anonymize prod data

---

config/ldes-delta-pusher/handle-regular-types.ts
docker-compose.yml

fix monitoring service bug, fix version for database, bump resource version, add tombstones to ldes so they know about deletion

fix monitoring service bug, fix version for database, bump resource version, add tombstones to ldes so they know about deletion

---

config/delta/decisions.js

fix delta rule for decisions: predicate was wrong and no reason to specify graph
Use the mock endpoint for adding a decision. see the delta being fired.

fix delta rule for decisions

---

config/cl-authorization/config.lisp
config/dispatcher/dispatcher.ex
config/migrations/2024/20240910094200-add-mock-admin-user.sparql
config/migrations/2024/20240910094800-add-bestuurseenheid-abb.sparql
docker-compose.dev.yml
docker-compose.yml

add impersonation service, add admin user, bump mock login, add impersonation config to mu-auth
See the linked PR
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/323

add impersonation service

---

config/ldes-delta-pusher/publisher.ts

Looking if all entities are published on the correct ldes stream to see if the problem that some data is not available in mandatendatabank is on our service side.
- /
- /

lmb-750: Not all entitiets are synced to mandatendatabank

---

config/migrations/2024/20240910114100-set-end-date-for-bestuursperiode-2019-2025.sparql

Quick fix migration missing optional.

Fix migration that sets end date bestuurorganen bestuursperiode 2019-2025

---

config/migrations/2024/20241003094700-cleanup-local-ocmw-organen.sparql

removes the local ocmw organen
reset your master to a spot where you still have the old organen, run migrations, set master to here, only the op new organen should be visible

also remove ocmw organen

---

config/migrations/2024/20241004092300-add-notification-codes.sparql
config/resources/system-notification.lisp

add missing notification type concept scheme, fix resources config
you can try this out with the linked pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/339

add missing notification type concept scheme, fix resources config

---

config/form-content/bestuursorgaan/form.ttl
config/migrations/2024/20241001152200-add-extra-bestuursorgaan-types.sparql

add new bestuursorgaan types and their mandates
Test using the frontend pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/333

add new bestuursorgaan types and their mandates

---

scripts/loket-to-lmb-transform/dropUnimportantGraphs.ts

keep emails from loket when processing loket data

keep emails from loket

---

docker-compose.yml

some services had missing logging config

add missing logging config

---

scripts/loket-to-lmb-transform/deleteUnwantedTypes.ts
scripts/loket-to-lmb-transform/dropUnimportantGraphs.ts

fixes to script after checking with latest loket db

---

config/migrations/2024/20241015134400-fix-fractie-type-relation.sparql

sometimes the incorrect predicate ext:fractieType was used.

fix fractietype

---

config/migrations/2024/20241015153904-update-bestuursperiode-2025-to-2024.sparql

update bestuursperiode to start/end at 2024
installatievergadering genereer rijen, create/update mandataris allows dates starting from 04-12-2024

update bestuursperiode to start/end at 2024

---

config/migrations/2024/20241018101300-remove-iv-for-districts.sparql

removes iv for districts
check these screens:

remove iv for districts

---

config/migrations/2024/20241017105500-2024-election-results/20241017110900-move-elections.sparql
config/migrations/2024/20241017105500-2024-election-results/20241017110901-move-persons.sparql

Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180

add limit to insert queries which should not matter at all

---

config/form-content/mandataris-edit/form.ttl

Update the required validation on the fractie selector field
Use with the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/381

lmb-922: update the validation for fractieselector

---

config/migrations/2024/20241029160700-fix-rudolf.sparql

fix rudolf

---

config/ldes-delta-pusher/ldes-instances.ts
config/ldes-delta-pusher/publisher.ts
config/migrations/2024/20241104112900-mark-public-public.sparql
docker-compose.yml

mark public graph public, don't require a bestuursorgaan in ldes watched graph, add default predicates to tombstones
see: https://github.com/redpencilio/ldes-delta-pusher-service/pull/10
- https://github.com/redpencilio/ldes-delta-pusher-service/pull/10

fixes in preparation for tombstone healing

---

config/cl-authorization/config.lisp
config/dispatcher/dispatcher.ex
config/resources/system-notification.lisp

Create a resource for gloabl system messages so we can crud these./ Only for admins!
Test it out togheter with the frontend.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/416

lmb-1010: Global system message

---

scripts/restart-virtuoso.sh

Add script to restart virtuoso

add script to restart virtuoso

---

docker-compose.yml

fix logging not cleaned up for ldes delta pusher

fix logging not cleaned up for ldes delta pusher

---

docker-compose.yml

The credentials for the email sender where not set. This is a PR so the email is already defined (from jira ticket Tim)
Cannot test without password, look if the value is good

lmb-793: update the email value where the emails should come from

---

config/cl-authorization/config.lisp

allow green valley to access gemeente data as ocmw

allow green valley to access gemeente data as ocmw

---

config/migrations/2024/20241129170918-fix-incorrect-names-v2.sparql

Fix another name.
See if the migration runs.

LMB-1119 fix another name

---

config/ldes-delta-pusher/initialization.ts
config/ldes-delta-pusher/ldes-instances.ts
config/ldes-delta-pusher/publisher.ts
docker-compose.yml

we reverted the changes for the ldes delta pusher but it turns out the problem was actually with the fragmentation producer. I added some optimizations though:
- more efficient transforming of predicates (using if instead of values + bind)
- added some https predicates to person predicate filtering in public just in case
This has been run on test successfully.
- create a checkpoint
- modify the dates of the checkpoint so it's > 2 days in the past
- heal from the checkpoint
- see that the healing creates no new instances
This has been done on test.

use new ldes pusher again

---

config/migrations/2024/20241206114054-fix-incorrect-names-v4.sparql

Some name changes again...
Just check if the migrations run.

LMB-1151 Correct names v4

---

config/cl-authorization/config.lisp

Add access workaround for remmicom.
Not sure how to test.

LMB-1155 add access workaround for remmicom

---

config/migrations/2024/20241206101139-add-access-sint-gillis-waas.sparql

Add vendor access to Sint-Gillis-Waas for vendor Inetum Realdomen.
Test if migration runs.

LMB-1148 add vendor access Sint-Gillis-Waas

---

config/form-content/persoon/form.ttl

Make rrn, geboortedatum and geslacht required.
Run this PR make sure you have restarted form-content service so the form is updated
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/439

Lmb 1076 | improve create person modal

---

config/migrations/2024/20241212143950-kortenaken-kim-gemeente.sparql
config/migrations/2024/20241212161752-kortenaken-modified-mandataris-voorzitter-gr-koen.sparql

Voorzitter was not updated for them => added modified triple for the mandataris
Missing gemeenteraad mandataris for Kim
- Voorzitter should be on Koen
- Negende lid should be Kim
- Both GR and RMW should have 19 mandatarissen

Lmb 1146 | rebound fix kortenaken

---

config/migrations/2024/20241210142814-fix-names-v5.sparql

Fix some more names.
Check if the migrations run.

LMB-1174 fix some more names

---

config/migrations/2024/20241211104654-heusden-zolder-bcsd-tombstone-mandataris.sparql

Rudi and Nico have a duplicate mandataris in the IV of Heusden-zolder for orgaan BCSD. These two need to be removed.
Still 11 people in BCSD but duplicates are removed

lmb-1172 | Remove mandataris heusden zolder BCSD

---

config/resources/external-besluit.lisp

Update the rechtsgrond to have the link of derivedFrom so we can show this link for the user 
Togheter with the frontend
- hhttps://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/444
- https://github.com/lblod/app-mandatees-decisions/pull/13

lmb-1184: add derived from to the rechtsgrond domain

---

config/migrations/2024/20241213095000-use-gemeente-fractie-uris.sparql

use gemeente fractie uris in ocmw too
Open a gemeente that has already completed their iv, e.g. aarschot and see that the fractie uris in the ocmw are now the ones in the gemeente and that the mandatarissen still have fracties

use gemeente fractie uris in ocmw too

---

config/migrations/2024/20241213132507-fix-delete-mandatarissen-sint-gillis-waas.sparql

fix missing modified and deleted timestamps, so it gets published on ldes

fix missing modified and deleted timestamps

---

config/migrations/2024/20241216090000-denderleeuw-duplicate-mandatarissen-iv.sparql

Remove the duplicates
See if there are any duplicsates in the Gemeente IV and double check the start date

lmb-1194: Denderleeuw fix duplciate mandatarissen

---

config/migrations/2024/20241217091309-names-sint-gillis-waas.sparql

Update these first names.
When migration has run name shsoul not be `Jan Astrid` and `Marieta Leopoldina`

lmb-1196: Sint-Gillis-Waas Jan & Marieta

---

config/migrations/2024/20241219102800-blankenberge-set-end-date-for.sparql

Mitch and Bjorn mandates need to be ended o request of Tim after LB standup.
Status should be beeindigd and end date should be 15/12/2024
**Mitch**
**Bjorn**

lmb-1268: end mandataris in blankenberge for

---

config/migrations/2024/20241220133600-kerremans.sparql

LMB-1269 : migration jaime ipv jamie

---

config/migrations/2024/20241220104800-min-max-for-single-mandates.sparql

add min/max for single mandates
Aalter did not have min/max for voorzitters. you can check there that the numbers are now correct

add min/max for single mandates

---

config/migrations/2025/20250115125700-missing-persons/20250115125700-missing-persons-antwerpen.sparql
config/migrations/2025/20250115125700-missing-persons/20250115125701-move-to-target.sparql
config/migrations/2025/20250115125700-missing-persons/20250115125702-drop-temp.sparql
config/migrations/2025/20250115125700-missing-persons/20250115125703-fix-name.sparql

add missing persons to graphs where they are used in election results
look for the people in the ticket. they should all be findable in the new legislature of gemeente antwerpen

add missing persons to graphs where they are used in election results

---

config/form-content/mandataris-edit/form.ttl
config/migrations/2025/20250120112000-update-end-date-of-bestuursorganen-blankenberge.sparql
config/migrations/2025/20250120112001-update-end-date-of-mandatarissen-blankenberge.sparql

Severity level must be warning for start and end date of a mandataris
Run togheter with the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/464

lmb-1302 | add a severity level to end and start date for  a mandataris

---

config/migrations/2025/20250128142300-genesius-rode-voorzitter.sparql

Sint-Genesius-Rode selected the wrong voorzitter for Gemeenteraad. Change the person and update the modified timestamp.
1. Run the migrations
2. Remove cache 
3. Frontend should show Anne as voorzitter for GR

lmb-1330 | change person of mandataris + update dcterms:modified

---

config/migrations/2025/20250203131656-fix-name-kruibeke-beveren-zwijndrecht.sparql

Fix a wrong name.
I only updated it in Kruibeke-Beveren-Zwijndrecht. The person also exists in Beveren, but since that is old data, I did not change it there.
Check if migration runs. 
You can login to Kruibeke-Beveren-Zwijndrecht and check Kathleen De Schepper is now Katleen De Schepper.

LMB-1345 fix name

---

config/migrations/2025/20250207161400-remove-duplicate-modifieds.sparql
config/migrations/2025/20250207161401-update-ocmw-mandatarissen-in-gemeente.sparql

removes duplicate modified dates and makes the gemeente mandatarissen mirror the true ones in the ocmw again.

fix ldes healing

---

config/migrations/2025/20250210155600-fix-name-antwerpen.sparql

fix name antwerpen
go to district antwerpen, see the name was changed in the districtsraad

fix name antwerpen

---

config/migrations/2025/20250211093400-fix-manual-besluit-links.sparql

fix links for gr gent, schepenen sint-martens-latem, new schepenen hooglede
visit those communes and check their links

fix manual links besluit

---

config/migrations/2025/20250211194039-remove-link-burgemeester-voorzitter-bv.sparql
config/migrations/2025/20250212112004-remove-end-date-corrupted-voorzitters-vb.sparql
config/migrations/2025/20250212132947-remove-split-voorzitters-vb.sparql
config/migrations/2025/20250212133406-remove-split-voorzitter-vb-Lierde.sparql

There were some issues with te fact that the voorzitter of the VB was linked to both the burgemeester and the aangewezen burgemeester.
To solve this the link between burgemeesters and voorzitter VB was removed. 
Also some corrupted data was restored. 
Two queries where used to find issues with voorzitters VB
The first query finds bestuurseenheden that had a voorzitter VB, but don't have one at this time. We just remove the end date of these mandatarissen
``` …
```

Ben/lmb 1359 Fix issues voorzitter VB

---

config/reports/helpers.js
config/reports/shacl-report.js
config/reports/shacl/mandataris_1_1.ttl
config/reports/shacl/mandataris_1_14.ttl
config/resources/shacl-report.lisp

Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180

add more data to validations

---

config/resources/external-besluit.lisp

Add predicate to mark bestuurseenheden as locally managed.
See frontend.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/494

LMB-1245 add locally managed predicate on bestuurseenheid

---

docs/LDES.md

updated docs for ldes
does it sound right?

update docs for ldes

---

config/migrations/2025/20250603090000-change-end-dates.sparql

sets the touched end dates one second back
you could do a query to check the minutes and seconds of the mandatarissen we touched but I think a quick check of a couple mandatarissen should be fine

set touched end dates one second back

---

docker-compose.yml

Release: update mandataris-service and frontend image

---

config/migrations/2025/20250315151700-fix-besluit-but-not-bekrachtigd.sparql

fix link to besluit exists but not bekrachtigd
check gent. should not contain niet bekrachtigde mandatarissen in gemeenteraad

fix link to besluit exists but not bekrachtigd

---

config/cl-authorization/config.lisp
config/dispatcher/dispatcher.ex
config/resources/concept-scheme.lisp
docker-compose.dev.yml
docker-compose.yml

Update the domain so we can manage codelists.
Togheter with the frontend (look at frontend PR on how to test)
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/483
- https://github.com/lblod/concept-scheme-service/pull/1

Lmb 1232 management of codelists

---

config/reports/shacl/mandataris_1_11.ttl
config/reports/shacl/mandataris_1_12.ttl
config/reports/shacl/mandataris_1_13.ttl
config/reports/shacl/mandataris_1_14.ttl

binding start and binding einde in these validation rules don't matter as we are only providing data from the current legislature
run the validations, they still work but now don't highlight e.g. gent.

binding start and binding einde don't matter as we are only providing data from the current legislature

---

config/dispatcher/dispatcher.ex
docker-compose.dev.yml
docker-compose.yml

We want to add this new service that will flag conflicting persons and fix person uris when the identifier matches.
Run it together with your local merge-person-service
- https://github.com/lblod/merge-person-service/pull/3

LMB-1453 | Merge person service

---

config/migrations/2025/20250306090000-change-end-dates.sparql
config/migrations/2025/20250325132000-fix-mandataris-start-dates.sparql
config/migrations/2025/20250325165400-set-bestuursorgaan-start-again.sparql
config/migrations/2025/20250326095500-set-end-dates-old-orgs.sparql
config/migrations/2025/20250326105400-besluit-but-not-bekrachtigd.sparql

fix mandatarissen with incorrect start dates and fix bestuursorgaan start dates corresponding to those mandatarissen
check the bestuursorganen in the list of this ticket and make sure their start dates (mandataris and orgaan) are fine
This query should only give you results that make sense
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT distinct ?label ?clasL ?start ?clas2L ?start2 WHERE {
?bestuurseenheid skos:prefLabel ?label.
?orgT mandaat:isTijdspecialisatieVan / besluit:bestuurt ?bestuurseenheid.
?orgT lmb:heeftBestuursperiode …
```

fix start dates mandatarissen

---

config/migrations/2025/20250331151900-politieraad-official-codes.sparql
config/migrations/2025/20250331160900-fix-politieraad-mandaten/20250331160900-delete-politieraad-voorzitters.sparql
config/migrations/2025/20250331160900-fix-politieraad-mandaten/20250331160901-new-politieraad-mandaten.graph
config/migrations/2025/20250331160900-fix-politieraad-mandaten/20250331160901-new-politieraad-mandaten.ttl
config/migrations/2025/20250331160900-fix-politieraad-mandaten/20250331160902-move-mandaten.sparql
config/migrations/2025/20250331160900-fix-politieraad-mandaten/20250331160903-cleanup.sparql

use official codes for politieraad
go to kruisem, add politieraadslid (and see voorzitter is also available)
go to oudenaarde, see the politieraadslid from kruisem

use official codes for politieraad

---

docker-compose.yml

bumps form content service so we can use the new way of listing instances

bump form-content

---

docker-compose.yml

bump deliver email service
drc pull, does it work?

bump deliver email service

---

config/reports/helpers.js

fix validation report cleanup by splitting into two queries
run the validation report on test in aarschot. it should now complete almost instantly again.

fix validation report cleanup by splitting into two queries

---

config/migrations/2025/20250425082400-add-person-display-types.sparql

new display types for links to persons
see linked pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/548

add person display types

---

config/form-content/persoon-extra-info/form.ttl
config/form-content/persoon/form.ttl

Split off foaf name into separate form
see linked pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/552

split foaf name into separate form

---

config/migrations/2025/20250505154900-add-flag-for-faciliteitengemeenten.sparql
config/migrations/2025/20250505154901-update-min-houders.sparql
config/op-consumer/mapping/queries/op2dl/pass/pass-without-lmb-properties.sparql

Vast bureau aantalHouders value is to low for ocmw's not in edge of brussels + Voeren. Set the value to the # of schepen plus 1.
1. First run the flag migration to make it easier to select the not faciliteitengemeente
2. When running this query you'll see that noone has changed the amount through the UI (this is also removed from UI now)
3. When running the migrations in the PR all values should be plus 1
```sparql
PREFIX extlmb: <http://mu.semte.ch/vocabularies/ext/lmb/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT …
```

LMB 1507 | Up the vb houders by # schepen plus one

---

config/reports/helpers.js
config/reports/shacl-report.js
config/reports/sparql/mandataris_1_3.ttl
config/reports/sparql/mandataris_2_3.ttl

when running validations on large municipalities, they broke. Test them on gent.
also, because of the difference in start/end dates, 2 validations had issues. I jumped through some hoops to get them fixed
run the validations on gent and see they now succeed

fix validations break on large municipalities

---

config/reports/sparql/mandataris_1_15.ttl
config/reports/sparql/mandataris_1_16.ttl
config/reports/sparql/mandataris_1_19.ttl
config/reports/sparql/mandataris_1_2.ttl
config/reports/sparql/mandataris_1_3.ttl
config/reports/sparql/mandataris_1_9.ttl
config/reports/sparql/mandataris_2_3.ttl

better validation messages and fixes to some queries
run validations in some eenheden

improve validations some more

---

config/reports/shacl-report.js
config/reports/sparql/mandataris_1_16.ttl

add result uri to list for easy debugging
allow any replacement with start date >= replacement date instead of exact date
add a replacement but with a later start date (and one with a start date that is too early)

validatie improvements after final check

---

config/migrations/2025/20250521083700-fix-duplicate-person-zele.sparql

fix for a person being duplicated in Zele. 
go to ocmw zele in the previous period and check that you still find bo as a member of rmw after running migrations and restarting resources and cache, same for current period and gemeente. person uri should be the same for both and a tombstone should be there for the old uri.

fix duplicate person zele

---

config/migrations/2025/20250703105540-fix-name.sparql

Fix spelling mistake in family name of person.
Check if the migration runs.

LMB-1682 add migration to fix name

---

config/reports/sparql/mandataris_1_3.ttl

take min date of problematic cases per mandate, since the date will receive an added day, use 30-12-2025 as end date

minor improvements to mandataris count validation

---

config/migrations/2025/20250710083900-fix-rijkevorsel-oostkamp-mayor.sparql

publication status was incorrectly set to effectief instead of bekrachtigd for rijkevorsel and oostkamp in previous migration
view mayors of oostkamp and rijkevorsel

fix mayor oostkamp and rijkevorsel publication status

---

config/modified/config.ts
docker-compose.yml

this bumps the frontend, mandataris, form-content and modified services to their latest version and also limits the modifieds being set to those in application graphs.
general testing of the app

bump services for testing

---

config/form-content/config.ts

Config added so it can be dynamic
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/597
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/597
- https://github.com/lblod/form-content-service/pull/89

lmb-1652: add config file for illegal uris

---

README.md

Update the readme so future developers know how to run the stack
RTFM
- https://github.com/lblod/form-content-service/pull/90
- https://github.com/lblod/mandataris-service/pull/123

LMB-1623 | Update readme

---

config/cl-authorization/config.lisp
config/dispatcher/dispatcher.ex
config/reports/sparql/mandataris_1_3.ttl
config/resources/shacl-report.lisp

allow silencing validations
see linked pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/606

allow silencing validations

---

config/migrations/2025/20250902144800-fix-start-end-datetimes.sparql

fixes the start and endtimes of mandatarissen in current period with an odd start/end time
go to willebroek, see that the validationerror is gone, inspect mandatarissen that became independent

fix start and endtimes mandatarissen

---

config/migrations/2025/20250918145000-correct-mandaat-cbs-antwerpen.sparql

This mnadataris has ended but always had the wrong mandaat. Change it from toegevoegde to schepen.
- Check Els in CBS  antwerpen => toegvoegde
- Run migrations
- Check again should be schepen

feat: migration to change mandaat els in antwerpen
